services:
  java-chrome-app-api:
    build:
      dockerfile: Dockerfile
    container_name: java-chrome-app-api
    shm_size: 2gb
#    ports:
#      - "18080:18080"
#      - "60001:60001"
#      - "1883:1883"
    networks:
      - my-network
    volumes:
      - /etc/localtime:/etc/localtime
      - /www/dk_project/dk_app/java-chrome-app-api/app:/app
    environment:
      - TZ=Asia/Shanghai
    working_dir: /app
    # 运行应用
    command: java -jar /app/app.jar
networks:
  my-network:
    name: wechat-api
    enable_ipv6: true
    driver: bridge
