services:
  java-chrome-app-system:
#    build:
#      dockerfile: Dockerfile-system
    image: selenium/standalone-chrome
    container_name: java-chrome-app-system
    shm_size: 2gb
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
#      - 最大会话时间
      - SE_NODE_MAX_SESSIONS=20
#      - 最大并发会话时间
      - SE_NODE_OVERRIDE_MAX_SESSIONS=10
#      - 会话超时时间
      - SE_NODE_SESSION_TIMEOUT=300
#      - 理运行时间超过 2 小时的浏览器和超过 1 天的文件
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
#      - 默认值3600（1小时），清理间隔（秒）。
      - SE_BROWSER_LEFTOVERS_INTERVAL_SECS=3600
#      - 默认值7200（2小时），运行时间超过该时间的浏览器将被终止。
      - SE_BROWSER_LEFTOVERS_PROCESSES_SECS=7200
#      - 默认值1（1天），基于Chrome的浏览器生成的文件/tmp将在此天数后
      - SE_BROWSER_LEFTOVERS_TEMPFILES_DAYS=1
#      - 默认值1（1天），基于Chrome的浏览器生成的文件/tmp将在此天数后
      - TZ=Asia/Shanghai
      # 子路径
      - SE_SUB_PATH=/chrome-system-ui/
    networks:
      my-network:
        ipv4_address: 172.20.0.24

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
